name: Vulnerable Issue
on: 
  issue_comment:
  workflow_dispatch:

jobs:
  echo-body:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ github.event.comment.body }}'
